/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Sign-in` | `/Sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Sign-up` | `/Sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/Insights` | `/Insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/Settings` | `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/Subscriptions` | `/Subscriptions`; params?: Router.UnknownInputParams; } | { pathname: `/subscriptions/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/Sign-in` | `/Sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/Sign-up` | `/Sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/Insights` | `/Insights`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/Settings` | `/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/Subscriptions` | `/Subscriptions`; params?: Router.UnknownOutputParams; } | { pathname: `/subscriptions/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/Sign-in${`?${string}` | `#${string}` | ''}` | `/Sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/Sign-up${`?${string}` | `#${string}` | ''}` | `/Sign-up${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(tabs)'}/Insights${`?${string}` | `#${string}` | ''}` | `/Insights${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(tabs)'}/Settings${`?${string}` | `#${string}` | ''}` | `/Settings${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(tabs)'}/Subscriptions${`?${string}` | `#${string}` | ''}` | `/Subscriptions${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Sign-in` | `/Sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Sign-up` | `/Sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/Insights` | `/Insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/Settings` | `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/Subscriptions` | `/Subscriptions`; params?: Router.UnknownInputParams; } | `/subscriptions/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/subscriptions/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
